/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./**/templates/**/*.html", "./core/forms.py"],
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        customLightForest: {
          ...require("daisyui/src/theming/themes")["corporate"],
          primary: '#506a63',
          secondary: '#1DB88E',
          accent: '#1DB8AB',
          neutral: '#506a63',
          'base-200': '#506a63',
          'base-300': '#19362D',
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
};
