# Generated by Django 5.1.3 on 2026-05-23 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailactivitytype',
            name='form',
            field=models.CharField(blank=True, choices=[('SeedPurchaseDetailsForm', 'Tree Seed Purchase Details'), ('Test1', 'Internal Test Form'), ('QuarantineTesting', 'Quarantine Testing'), ('BranchHQTransportForm', 'Branch to HQ Transportation'), ('HQNurserySeedTransportationForm', 'HQ to Nursery Seed Transportation'), ('FirewoodCustomerTransportForm', 'Transporting sold firewood to customer'), ('LogProductionSawmillTransportForm', 'Log Transportation from Production Site to Sawmill'), ('NurserySubCompartmentTransportForm', 'Nursery Sub Compartment Transport'), ('SeedSourceBranchTransportForm', 'Seed Source Branch Transport'), ('SeedBranchReceivingForm', 'Seed Receiving Form'), ('NurserySeedReceivingForm', 'Nursery Seed Receiving Details'), ('LogReceivingForm', 'Receiving logs/ approve sent logs'), ('SowingForm', 'Sowing Form'), ('GerminatedSeedForm', 'Germinated Seed Form'), ('SeedlingNurserySale', 'Seedling Sale Form'), ('GradingSeedlingForm', 'Grading Seedling Form'), ('HQSeedReceivingForm', 'HQ Seed Receiving Details'), ('SeedlingReceivingForm', 'Seedling Receiving Details'), ('SeedSaleForm', 'Seed Sale'), ('GradingForm', 'Grading Form'), ('HandoffForm', 'Handoff Planted Seedling Form'), ('BeatupForm', 'Beatup Form'), ('GiveAwayForm', 'Surplus by-products Giveaway'), ('ForestInventoryForm', 'Forest Inventory'), ('SurvivalCountForm', 'Survival Count Form'), ('LowThinningForm', 'Low Thinning Form'), ('HighThinningForm', 'High Thinning Form'), ('PreCommercialCoppiceSinglingForm', 'Pre Commercial Coppice Singling Form'), ('CommercialSinglingForm', 'Commercial Coppice Singling Form'), ('SaleCoppiceForm', 'Coppice Sale Form'), ('SaleThinningForm', 'Thinning Sale Form'), ('RegisterProductForm', 'Register Products'), ('TimelyHarvestingForm', 'Timely Harvested Product'), ('SaleEachProductForm', 'Sale of each product'), ('SaleDifferentProduct', 'Sale of different product'), ('StampageSaleForm', 'Sale at Stampage'), ('OperationalForestInventoryForm', 'Operational Forest Inventory'), ('DownTimeForm', 'Recording Down Time Form'), ('JobOpportunityForm', 'Record Created Job Opportunities'), ('DepoFactoryInputForm', 'Depot To Factory Input Form'), ('FactoryDailyProductionForm', 'Factory daily lumber production'), ('PlantationSiteSelectionForm', 'Plantation Site Selection Report'), ('LumberStoredForm', 'Lumber Stored')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='name',
            field=models.CharField(choices=[('SeedPurchaseDetailsForm', 'Tree Seed Purchase Details'), ('Test1', 'Internal Test Form'), ('QuarantineTesting', 'Quarantine Testing'), ('BranchHQTransportForm', 'Branch to HQ Transportation'), ('HQNurserySeedTransportationForm', 'HQ to Nursery Seed Transportation'), ('FirewoodCustomerTransportForm', 'Transporting sold firewood to customer'), ('LogProductionSawmillTransportForm', 'Log Transportation from Production Site to Sawmill'), ('NurserySubCompartmentTransportForm', 'Nursery Sub Compartment Transport'), ('SeedSourceBranchTransportForm', 'Seed Source Branch Transport'), ('SeedBranchReceivingForm', 'Seed Receiving Form'), ('NurserySeedReceivingForm', 'Nursery Seed Receiving Details'), ('LogReceivingForm', 'Receiving logs/ approve sent logs'), ('SowingForm', 'Sowing Form'), ('GerminatedSeedForm', 'Germinated Seed Form'), ('SeedlingNurserySale', 'Seedling Sale Form'), ('GradingSeedlingForm', 'Grading Seedling Form'), ('HQSeedReceivingForm', 'HQ Seed Receiving Details'), ('SeedlingReceivingForm', 'Seedling Receiving Details'), ('SeedSaleForm', 'Seed Sale'), ('GradingForm', 'Grading Form'), ('HandoffForm', 'Handoff Planted Seedling Form'), ('BeatupForm', 'Beatup Form'), ('GiveAwayForm', 'Surplus by-products Giveaway'), ('ForestInventoryForm', 'Forest Inventory'), ('SurvivalCountForm', 'Survival Count Form'), ('LowThinningForm', 'Low Thinning Form'), ('HighThinningForm', 'High Thinning Form'), ('PreCommercialCoppiceSinglingForm', 'Pre Commercial Coppice Singling Form'), ('CommercialSinglingForm', 'Commercial Coppice Singling Form'), ('SaleCoppiceForm', 'Coppice Sale Form'), ('SaleThinningForm', 'Thinning Sale Form'), ('RegisterProductForm', 'Register Products'), ('TimelyHarvestingForm', 'Timely Harvested Product'), ('SaleEachProductForm', 'Sale of each product'), ('SaleDifferentProduct', 'Sale of different product'), ('StampageSaleForm', 'Sale at Stampage'), ('OperationalForestInventoryForm', 'Operational Forest Inventory'), ('DownTimeForm', 'Recording Down Time Form'), ('JobOpportunityForm', 'Record Created Job Opportunities'), ('DepoFactoryInputForm', 'Depot To Factory Input Form'), ('FactoryDailyProductionForm', 'Factory daily lumber production'), ('PlantationSiteSelectionForm', 'Plantation Site Selection Report'), ('LumberStoredForm', 'Lumber Stored')], max_length=50),
        ),
        migrations.CreateModel(
            name='PlantedSeedlingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seedling_type', models.CharField(max_length=100)),
                ('planted_quantity', models.PositiveIntegerField()),
                ('survived_quantity', models.PositiveIntegerField(default=0)),
                ('planting_date', models.DateField()),
                ('rainfall_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('plantation_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('planted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planted Seedling Report',
                'verbose_name_plural': 'Planted Seedling Reports',
            },
        ),
    ]
