# Generated by Django 5.1.3 on 2026-05-24 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_detailactivitytype_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsale',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.batch'),
        ),
    ]
