# Generated by Django 5.1.3 on 2026-05-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_itemsale_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsale',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.batch', verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='itemsale',
            name='unit_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Unit Price'),
        ),
    ]
