# Generated by Django 5.1.3 on 2026-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_itemsale_batch_alter_itemsale_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSyncMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sync_images/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Sync Metadata',
                'verbose_name_plural': 'Image Sync Metadata',
                'ordering': ['-created_at'],
            },
        ),
    ]
