# Generated by Django 5.1.3 on 2026-06-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_imagesyncmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrecieve',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
